

CREATE TABLE issues (
    id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    author INTEGER NOT NULL REFERENCES users ON DELETE CASCADE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
)