
CREATE TABLE comments (
    id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    body TEXT NOT NULL,
    author INTEGER NOT NULL REFERENCES users ON DELETE CASCADE,
    issues INTEGER NOT NULL REFERENCES issues ON DELETE CASCADE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
)